"""
CRUD operations for Tourist model

This module provides database operations for creating, reading, updating,
and deleting tourist records. It serves as the data access layer for
tourist-related API endpoints.
"""

from sqlalchemy.orm import Session
from typing import Optional
from datetime import datetime
from ..db import models
from ..schemas import tourist as schemas


def create_tourist(db: Session, tourist: schemas.TouristCreate) -> models.Tourist:
    """
    Create a new tourist record in the database
    
    This function creates a new Tourist object using the provided data,
    saves it to the database, and returns the newly created record with
    all database-generated fields (like UUID and timestamps).
    
    Args:
        db: Database session for executing the operation
        tourist: TouristCreate schema containing the tourist data
        
    Returns:
        models.Tourist: The newly created tourist record with generated fields
        
    Raises:
        SQLAlchemyError: If database operation fails
        
    Example:
        >>> tourist_data = TouristCreate(
        ...     name="Alice Johnson",
        ...     kyc_hash="kyc_abc123",
        ...     emergency_contact={"phone": "+1234567890"},
        ...     trip_end_date=datetime(2025, 9, 22)
        ... )
        >>> new_tourist = create_tourist(db, tourist_data)
        >>> print(new_tourist.id)  # Auto-generated UUID
    """
    # Step 1: Create a new SQLAlchemy Tourist object using the schema data
    db_tourist = models.Tourist(
        name=tourist.name,
        kyc_hash=tourist.kyc_hash,
        emergency_contact=tourist.emergency_contact,
        trip_end_date=tourist.trip_end_date
        # Note: id and created_at are auto-generated by the database
    )
    
    # Step 2: Add the new object to the database session
    db.add(db_tourist)
    
    # Step 3: Commit the session to save the data to the database
    db.commit()
    
    # Step 4: Refresh the session to get database-generated values
    # This populates the auto-generated UUID id and created_at timestamp
    db.refresh(db_tourist)
    
    # Step 5: Return the newly created tourist object with all fields populated
    return db_tourist


def get_tourist(db: Session, tourist_id: str) -> Optional[models.Tourist]:
    """
    Retrieve a single tourist by their ID
    
    This function queries the database for a tourist with the specified ID
    and returns the tourist record if found, or None if not found.
    
    Args:
        db: Database session for executing the query
        tourist_id: String representation of the tourist's UUID
        
    Returns:
        Optional[models.Tourist]: The tourist record if found, None otherwise
        
    Example:
        >>> tourist = get_tourist(db, "123e4567-e89b-12d3-a456-426614174000")
        >>> if tourist:
        ...     print(f"Found tourist: {tourist.name}")
        ... else:
        ...     print("Tourist not found")
    """
    return db.query(models.Tourist).filter(models.Tourist.id == tourist_id).first()


def get_tourist_by_kyc_hash(db: Session, kyc_hash: str) -> Optional[models.Tourist]:
    """
    Retrieve a tourist by their KYC hash
    
    This function is useful for checking if a tourist with a specific
    KYC hash already exists in the system to prevent duplicate registrations.
    
    Args:
        db: Database session for executing the query
        kyc_hash: The KYC hash to search for
        
    Returns:
        Optional[models.Tourist]: The tourist record if found, None otherwise
    """
    return db.query(models.Tourist).filter(models.Tourist.kyc_hash == kyc_hash).first()


def list_tourists(db: Session, skip: int = 0, limit: int = 100) -> list[models.Tourist]:
    """
    Retrieve a list of tourists with pagination
    
    This function returns a paginated list of all tourists in the database,
    useful for dashboard views and administrative operations.
    
    Args:
        db: Database session for executing the query
        skip: Number of records to skip (for pagination)
        limit: Maximum number of records to return
        
    Returns:
        list[models.Tourist]: List of tourist records
    """
    return db.query(models.Tourist).offset(skip).limit(limit).all()


def update_tourist_emergency_contact(db: Session, tourist_id: str, emergency_contact: dict) -> Optional[models.Tourist]:
    """
    Update a tourist's emergency contact information
    
    This function allows updating the emergency contact information
    for an existing tourist record.
    
    Args:
        db: Database session for executing the operation
        tourist_id: String representation of the tourist's UUID
        emergency_contact: New emergency contact information
        
    Returns:
        Optional[models.Tourist]: Updated tourist record if found, None otherwise
    """
    db_tourist = get_tourist(db, tourist_id)
    if db_tourist:
        db_tourist.emergency_contact = emergency_contact
        db.commit()
        db.refresh(db_tourist)
    return db_tourist


def create_location_log(db: Session, tourist_id: str, location: schemas.LocationCreate) -> models.LocationLog:
    """
    Create a new location log entry for a tourist
    
    This function creates a LocationLog record with the tourist's current
    GPS coordinates and timestamp. Used for both regular location tracking
    and panic button location logging.
    
    Args:
        db: Database session for executing the operation
        tourist_id: String representation of the tourist's UUID
        location: LocationCreate schema containing latitude and longitude
        
    Returns:
        models.LocationLog: The newly created location log record
        
    Raises:
        SQLAlchemyError: If database operation fails
        
    Example:
        >>> location_data = LocationCreate(latitude=40.7128, longitude=-74.0060)
        >>> log_entry = create_location_log(db, "123e4567-e89b-12d3", location_data)
        >>> print(f"Logged location at {log_entry.timestamp}")
    """
    # Step 1: Create a new SQLAlchemy LocationLog object
    db_location_log = models.LocationLog(
        tourist_id=tourist_id,
        latitude=location.latitude,
        longitude=location.longitude,
        timestamp=datetime.now(timezone.utc)  # Set current UTC timestamp
    )
    
    # Step 2: Add the new object to the database session
    db.add(db_location_log)
    
    # Step 3: Commit the session to save the data to the database
    db.commit()
    
    # Step 4: Refresh the session to get any database-generated values
    db.refresh(db_location_log)
    
    # Step 5: Return the newly created location log object
    return db_location_log


def get_latest_location_by_tourist_id(db: Session, tourist_id: str) -> Optional[models.LocationLog]:
    """
    Get the latest location log entry for a specific tourist
    
    This function retrieves the most recent location log for the specified
    tourist, ordered by timestamp in descending order.
    
    Args:
        db: Database session for executing the query
        tourist_id: String representation of the tourist's UUID
        
    Returns:
        Optional[models.LocationLog]: Latest location log if found, None otherwise
    """
    return db.query(models.LocationLog).filter(
        models.LocationLog.tourist_id == tourist_id
    ).order_by(models.LocationLog.timestamp.desc()).first()


def get_location_logs_by_tourist_id(db: Session, tourist_id: str, limit: int = 100) -> list[models.LocationLog]:
    """
    Get location logs for a specific tourist with pagination
    
    Args:
        db: Database session for executing the query
        tourist_id: String representation of the tourist's UUID
        limit: Maximum number of records to return
        
    Returns:
        list[models.LocationLog]: List of location log records
    """
    return db.query(models.LocationLog).filter(
        models.LocationLog.tourist_id == tourist_id
    ).order_by(models.LocationLog.timestamp.desc()).limit(limit).all()


def get_location_history(db: Session, tourist_id: str, limit: int = 100) -> list[models.LocationLog]:
    """
    Get location history for ML anomaly detection
    
    Args:
        db: Database session for executing the query
        tourist_id: String representation of the tourist's UUID
        limit: Maximum number of records to return (default 100 for ML analysis)
        
    Returns:
        list[models.LocationLog]: List of location log records ordered by timestamp desc
    """
    return db.query(models.LocationLog).filter(
        models.LocationLog.tourist_id == tourist_id
    ).order_by(models.LocationLog.timestamp.desc()).limit(limit).all()
